spring.application.name=backend


# Korriger database URL - BYTT UT 'mysqldatabase' med faktisk databasenavn!
spring.datasource.url=jdbc:sqlserver://frisordatabase.database.windows.net:1433;database=mysqldatabase;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30

# Brukernavn (uten @frisordatabase her - legg det kun i URL hvis nødvendig)
spring.datasource.username=sqladmin

# Passord (UTEN krøllparenteser!)
spring.datasource.password=Jhin140893

# Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect





spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=bergenfrisorr@gmail.com
spring.mail.password=abzq sfmj wrkz qibv

# Disse innstillingene er nødvendige for port 465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.properties.mail.smtp.ssl.enable=true